use_frameworks!

platform :ios, '13.0'

target 'PapilonIDRecognitioniOS_Example' do
  pod 'PapilonIDRecognitioniOS', :path => '../'

  target 'PapilonIDRecognitioniOS_Tests' do
    inherit! :search_paths

    
  end
end
